import { gradients } from "@/constants/colors";
import type { LoyaltyRank } from "@/types";

export const loyaltyRanks: LoyaltyRank[] = [
  {
    id: "bronze",
    name: "Bronze",
    theme: "Seedling",
    minPoints: 0,
    maxPoints: 999,
    badge: "feather",
    plantStage: "Seedling",
    gradient: gradients.bronze,
    benefits: ["Starter ride rewards", "Basic eco tracker"],
  },
  {
    id: "silver",
    name: "Silver",
    theme: "Sprout",
    minPoints: 1000,
    maxPoints: 2499,
    badge: "activity",
    plantStage: "Sprout",
    gradient: gradients.silver,
    benefits: ["Faster reward conversion", "Monthly rider badge"],
  },
  {
    id: "gold",
    name: "Gold",
    theme: "Sapling",
    minPoints: 2500,
    maxPoints: 4999,
    badge: "sun",
    plantStage: "Sapling",
    gradient: gradients.gold,
    benefits: ["Priority service advisories", "Bonus eco points"],
  },
  {
    id: "platinum",
    name: "Platinum",
    theme: "Tree",
    minPoints: 5000,
    maxPoints: 8999,
    badge: "cloud",
    plantStage: "Tree",
    gradient: gradients.platinum,
    benefits: ["Premium rank frame", "Higher conversion cap"],
  },
  {
    id: "diamond",
    name: "Diamond",
    theme: "Flowering Tree",
    minPoints: 9000,
    maxPoints: 15000,
    badge: "star",
    plantStage: "Flowering Tree",
    gradient: gradients.diamond,
    benefits: ["Top Eco Rider spotlight", "Best reward multiplier"],
  },
];
